# Logging configuration
logging.level.ru.qmbo=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Server configuration
server.port=8080

# FreeMarker configuration
spring.freemarker.suffix=.ftlh
spring.freemarker.cache=false